export const RentalVadodara = [
  {
    Avatar: "/house_1.jpg",
    Name: "John Smith",
    Characteristics: "2BHK",
    Rate: 15000,
    longitude: 73.1924,
    latitude: 22.3069,
    About: "A cozy 2BHK house available for rent in a quiet neighborhood.",
  },
  {
    Avatar: "/house_2.jpeg",
    Name: "Lisa Johnson",
    Characteristics: "3BHK",
    Rate: 20000,
    longitude: 73.2046,
    latitude: 22.3184,
    About: "Spacious 3BHK house with modern amenities, perfect for a family.",
  },
  {
    Avatar: "/house_3.jpg",
    Name: "Michael Patel",
    Characteristics: "1BHK",
    Rate: 12000,
    longitude: 73.1945,
    latitude: 22.314,
    About: "Affordable 1BHK house in a convenient location.",
  },
  {
    Avatar: "/house_4.jpg",
    Name: "Sarah Sharma",
    Characteristics: "4BHK",
    Rate: 25000,
    longitude: 73.1901,
    latitude: 22.3115,
    About: "Luxurious 4BHK house with a beautiful garden.",
  },
  {
    Avatar: "/house_5.jpg",
    Name: "David Gupta",
    Characteristics: "2BHK",
    Rate: 16000,
    longitude: 73.1992,
    latitude: 22.3177,
    About: "2BHK house with modern interiors and great views.",
  },
  {
    Avatar: "/house_6.jpg",
    Name: "Jessica Kumar",
    Characteristics: "3BHK",
    Rate: 21000,
    longitude: 73.1862,
    latitude: 22.3087,
    About: "Spacious 3BHK house with easy access to amenities.",
  },
  {
    Avatar: "/house_7.jpg",
    Name: "James Shah",
    Characteristics: "2BHK",
    Rate: 17000,
    longitude: 73.208,
    latitude: 22.3108,
    About: "Comfortable 2BHK house with a friendly neighborhood.",
  },
  {
    Avatar: "/house_8.jpg",
    Name: "Emily Joshi",
    Characteristics: "1BHK",
    Rate: 11000,
    longitude: 73.1819,
    latitude: 22.3056,
    About: "Affordable 1BHK house in a peaceful environment.",
  },
  {
    Avatar: "/house_9.jpg",
    Name: "Daniel Agrawal",
    Characteristics: "3BHK",
    Rate: 22000,
    longitude: 73.1913,
    latitude: 22.3008,
    About: "Spacious 3BHK house with modern amenities.",
  },
  {
    Avatar: "/house_10.jpg",
    Name: "Olivia Mehta",
    Characteristics: "2BHK",
    Rate: 16000,
    longitude: 73.2032,
    latitude: 22.3165,
    About: "2BHK house in a prime location, perfect for professionals.",
  },
];

export const RentalSurat = [
  {
    Avatar: "/house_1.jpg",
    Name: "Alex Patel",
    Characteristics: "2BHK",
    Rate: 14000,
    longitude: 72.8156,
    latitude: 21.1648,
    About:
      "A comfortable 2BHK house available for rent with easy access to transportation.",
  },
  {
    Avatar: "/house_2.jpeg",
    Name: "Sophia Shah",
    Characteristics: "3BHK",
    Rate: 18000,
    longitude: 72.8279,
    latitude: 21.1623,
    About:
      "Spacious 3BHK house in a peaceful neighborhood, ideal for families.",
  },
  {
    Avatar: "/house_3.jpg",
    Name: "William Desai",
    Characteristics: "1BHK",
    Rate: 10000,
    longitude: 72.8094,
    latitude: 21.1567,
    About: "Affordable 1BHK house for rent with nearby amenities.",
  },
  {
    Avatar: "/house_4.jpg",
    Name: "Ava Joshi",
    Characteristics: "4BHK",
    Rate: 22000,
    longitude: 72.8314,
    latitude: 21.1725,
    About:
      "Luxurious 4BHK house with a garden, perfect for a comfortable living experience.",
  },
  {
    Avatar: "/house_5.jpg",
    Name: "Liam Mehta",
    Characteristics: "2BHK",
    Rate: 16000,
    longitude: 72.8375,
    latitude: 21.1763,
    About: "2BHK house with modern interiors and scenic surroundings.",
  },
  {
    Avatar: "/house_6.jpg",
    Name: "Emma Kumar",
    Characteristics: "3BHK",
    Rate: 21000,
    longitude: 72.8212,
    latitude: 21.169,
    About: "Spacious 3BHK house in a family-friendly neighborhood.",
  },
  {
    Avatar: "/house_7.jpg",
    Name: "Noah Gupta",
    Characteristics: "2BHK",
    Rate: 15000,
    longitude: 72.8276,
    latitude: 21.1662,
    About:
      "Comfortable 2BHK house with easy access to shopping and dining options.",
  },
  {
    Avatar: "/house_8.jpg",
    Name: "Olivia Patel",
    Characteristics: "1BHK",
    Rate: 11000,
    longitude: 72.8137,
    latitude: 21.1589,
    About: "Affordable 1BHK house in a convenient location.",
  },
  {
    Avatar: "/house_9.jpg",
    Name: "Mason Shah",
    Characteristics: "3BHK",
    Rate: 20000,
    longitude: 72.8348,
    latitude: 21.1757,
    About: "Spacious 3BHK house with modern amenities, perfect for a family.",
  },
  {
    Avatar: "/house_10.jpg",
    Name: "Sophia Desai",
    Characteristics: "2BHK",
    Rate: 16000,
    longitude: 72.8217,
    latitude: 21.1628,
    About: "2BHK house in a prime location, suitable for professionals.",
  },
];

export const RentalAhmedabad = [
  {
    Avatar: "/house_1.jpg",
    Name: "Ethan Patel",
    Characteristics: "2BHK",
    Rate: 13000,
    longitude: 72.5875,
    latitude: 23.0221,
    About: "Cozy 2BHK house available for rent in a quiet residential area.",
  },
  {
    Avatar: "/house_2.jpeg",
    Name: "Olivia Shah",
    Characteristics: "3BHK",
    Rate: 17000,
    longitude: 72.6024,
    latitude: 23.0264,
    About: "Spacious 3BHK house with modern amenities, ideal for a family.",
  },
  {
    Avatar: "/house_3.jpg",
    Name: "Liam Desai",
    Characteristics: "1BHK",
    Rate: 9000,
    longitude: 72.5953,
    latitude: 23.026,
    About: "Affordable 1BHK house for rent in a convenient location.",
  },
  {
    Avatar: "/house_4.jpg",
    Name: "Emma Joshi",
    Characteristics: "4BHK",
    Rate: 21000,
    longitude: 72.5918,
    latitude: 23.0384,
    About: "Luxurious 4BHK house with a beautiful garden.",
  },
  {
    Avatar: "/house_5.jpg",
    Name: "Mason Mehta",
    Characteristics: "2BHK",
    Rate: 14000,
    longitude: 72.6039,
    latitude: 23.032,
    About: "2BHK house with modern interiors and great views.",
  },
  {
    Avatar: "/house_6.jpg",
    Name: "Sophia Kumar",
    Characteristics: "3BHK",
    Rate: 19000,
    longitude: 72.5952,
    latitude: 23.0433,
    About: "Spacious 3BHK house with easy access to amenities.",
  },
  {
    Avatar: "/house_7.jpg",
    Name: "Ava Gupta",
    Characteristics: "2BHK",
    Rate: 12000,
    longitude: 72.5965,
    latitude: 23.0331,
    About: "Comfortable 2BHK house with a friendly neighborhood.",
  },
  {
    Avatar: "/house_8.jpg",
    Name: "Noah Patel",
    Characteristics: "1BHK",
    Rate: 8500,
    longitude: 72.5823,
    latitude: 23.0238,
    About: "Affordable 1BHK house in a peaceful environment.",
  },
  {
    Avatar: "/house_9.jpg",
    Name: "William Shah",
    Characteristics: "3BHK",
    Rate: 20000,
    longitude: 72.5868,
    latitude: 23.0346,
    About: "Spacious 3BHK house with modern amenities.",
  },
  {
    Avatar: "/house_10.jpg",
    Name: "Olivia Desai",
    Characteristics: "2BHK",
    Rate: 14000,
    longitude: 72.6012,
    latitude: 23.0295,
    About: "2BHK house in a prime location, perfect for professionals.",
  },
];

export const LawyerVadodara = [
  {
    Avatar: "/lawyer_1.jpeg",
    Name: "John Smith",
    Characteristics: "Divorce Law",
    Rate: 2000,
    rating: 4.7,
    longitude: 73.1938,
    latitude: 22.3063,
    About:
      "John Smith specializes in Divorce Law and has a 4.7-star rating. He is dedicated to helping clients navigate the complexities of divorce proceedings.",
  },
  {
    Avatar: "/lawyer_2.jpeg",
    Name: "Lisa Johnson",
    Characteristics: "Criminal Defense",
    Rate: 2500,
    rating: 4.5,
    longitude: 73.2046,
    latitude: 22.3184,
    About:
      "Lisa Johnson is an experienced Criminal Defense attorney with a 4.5-star rating. She is committed to defending her clients' rights in criminal cases.",
  },
  {
    Avatar: "/lawyer_3.jpeg",
    Name: "Michael Patel",
    Characteristics: "Real Estate Law",
    Rate: 1800,
    rating: 4.8,
    longitude: 73.1945,
    latitude: 22.314,
    About:
      "Michael Patel specializes in Real Estate Law and holds a 4.8-star rating. He assists clients in navigating real estate transactions and legal matters.",
  },
  {
    Avatar: "/lawyer_4.jpeg",
    Name: "Sarah Sharma",
    Characteristics: "Family Law",
    Rate: 2200,
    rating: 4.6,
    longitude: 73.1901,
    latitude: 22.3115,
    About:
      "Sarah Sharma is a Family Law attorney with a 4.6-star rating. She is dedicated to helping families resolve legal issues with care and empathy.",
  },
  {
    Avatar: "/lawyer_5.jpeg",
    Name: "David Gupta",
    Characteristics: "Business Law",
    Rate: 2400,
    rating: 4.7,
    longitude: 73.1992,
    latitude: 22.3177,
    About:
      "David Gupta specializes in Business Law and has a 4.7-star rating. He assists businesses in legal matters to ensure their success.",
  },
  {
    Avatar: "/lawyer_6.jpeg",
    Name: "Jessica Kumar",
    Characteristics: "Immigration Law",
    Rate: 1900,
    rating: 4.9,
    longitude: 73.1862,
    latitude: 22.3087,
    About:
      "Jessica Kumar is an Immigration Law expert with a 4.9-star rating. She helps clients navigate immigration processes and achieve their goals.",
  },
  {
    Avatar: "/lawyer_7.jpeg",
    Name: "James Shah",
    Characteristics: "Intellectual Property",
    Rate: 2300,
    rating: 4.8,
    longitude: 73.208,
    latitude: 22.3108,
    About:
      "James Shah specializes in Intellectual Property Law with a 4.8-star rating. He assists clients in protecting their intellectual property rights.",
  },
  {
    Avatar: "/lawyer_8.jpeg",
    Name: "Emily Joshi",
    Characteristics: "Personal Injury",
    Rate: 2100,
    rating: 4.7,
    longitude: 73.1819,
    latitude: 22.3056,
    About:
      "Emily Joshi is a Personal Injury attorney with a 4.7-star rating. She fights for the rights of individuals injured due to negligence.",
  },
  {
    Avatar: "/lawyer_9.jpeg",
    Name: "Daniel Agrawal",
    Characteristics: "Estate Planning",
    Rate: 1700,
    rating: 4.6,
    longitude: 73.1913,
    latitude: 22.3008,
    About:
      "Daniel Agrawal specializes in Estate Planning and has a 4.6-star rating. He helps clients with estate and wealth preservation strategies.",
  },
  {
    Avatar: "/lawyer_10.jpeg",
    Name: "Olivia Mehta",
    Characteristics: "Environmental Law",
    Rate: 2600,
    rating: 4.4,
    longitude: 73.2032,
    latitude: 22.3165,
    About:
      "Olivia Mehta is an Environmental Law attorney with a 4.4-star rating. She is dedicated to environmental protection and legal advocacy.",
  },
];

export const LawyerSurat = [
  {
    Avatar: "/lawyer_1.jpeg",
    Name: "Alex Patel",
    Characteristics: "Divorce Law",
    Rate: 2200,
    rating: 4.6,
    longitude: 72.8156,
    latitude: 21.1648,
    About:
      "Alex Patel is an experienced Divorce Law attorney with a 4.6-star rating. He provides compassionate legal support during challenging times.",
  },
  {
    Avatar: "/lawyer_2.jpeg",
    Name: "Sophia Shah",
    Characteristics: "Criminal Defense",
    Rate: 2400,
    rating: 4.7,
    longitude: 72.8279,
    latitude: 21.1623,
    About:
      "Sophia Shah specializes in Criminal Defense and has a 4.7-star rating. She is committed to defending her clients' rights in criminal cases.",
  },
  {
    Avatar: "/lawyer_3.jpeg",
    Name: "William Desai",
    Characteristics: "Real Estate Law",
    Rate: 2100,
    rating: 4.8,
    longitude: 72.8094,
    latitude: 21.1567,
    About:
      "William Desai is a Real Estate Law expert with a 4.8-star rating. He assists clients in navigating real estate transactions and legal matters.",
  },
  {
    Avatar: "/lawyer_4.jpeg",
    Name: "Ava Joshi",
    Characteristics: "Family Law",
    Rate: 2300,
    rating: 4.5,
    longitude: 72.8314,
    latitude: 21.1725,
    About:
      "Ava Joshi is a Family Law attorney with a 4.5-star rating. She is dedicated to helping families resolve legal issues with care and empathy.",
  },
  {
    Avatar: "/lawyer_5.jpeg",
    Name: "Liam Mehta",
    Characteristics: "Business Law",
    Rate: 2500,
    rating: 4.9,
    longitude: 72.8375,
    latitude: 21.1763,
    About:
      "Liam Mehta specializes in Business Law and has a 4.9-star rating. He assists businesses in legal matters to ensure their success.",
  },
  {
    Avatar: "/lawyer_6.jpeg",
    Name: "Emma Kumar",
    Characteristics: "Immigration Law",
    Rate: 2000,
    rating: 4.4,
    longitude: 72.8212,
    latitude: 21.169,
    About:
      "Emma Kumar is an Immigration Law expert with a 4.4-star rating. She helps clients navigate immigration processes and achieve their goals.",
  },
  {
    Avatar: "/lawyer_7.jpeg",
    Name: "Noah Gupta",
    Characteristics: "Intellectual Property",
    Rate: 2600,
    rating: 4.7,
    longitude: 72.8015,
    latitude: 21.1526,
    About:
      "Noah Gupta specializes in Intellectual Property Law with a 4.7-star rating. He assists clients in protecting their intellectual property rights.",
  },
  {
    Avatar: "/lawyer_8.jpeg",
    Name: "Olivia Patel",
    Characteristics: "Personal Injury",
    Rate: 2200,
    rating: 4.8,
    longitude: 72.8137,
    latitude: 21.1589,
    About:
      "Olivia Patel is a Personal Injury attorney with a 4.8-star rating. She fights for the rights of individuals injured due to negligence.",
  },
  {
    Avatar: "/lawyer_9.jpeg",
    Name: "Mason Shah",
    Characteristics: "Estate Planning",
    Rate: 2300,
    rating: 4.6,
    longitude: 72.8348,
    latitude: 21.1757,
    About:
      "Mason Shah specializes in Estate Planning and has a 4.6-star rating. He helps clients with estate and wealth preservation strategies.",
  },
  {
    Avatar: "/lawyer_10.jpeg",
    Name: "Sophia Desai",
    Characteristics: "Environmental Law",
    Rate: 2100,
    rating: 4.5,
    longitude: 72.8217,
    latitude: 21.1628,
    About:
      "Sophia Desai is an Environmental Law attorney with a 4.5-star rating. She is dedicated to environmental protection and legal advocacy.",
  },
];

export const LawyerAhmedabad = [
  {
    Avatar: "/lawyer_1.jpeg",
    Name: "Ethan Patel",
    Characteristics: "Divorce Law",
    Rate: 2200,
    rating: 4.6,
    longitude: 72.5875,
    latitude: 23.0221,
    About:
      "Ethan Patel is an experienced Divorce Law attorney with a 4.6-star rating. He provides compassionate legal support during challenging times.",
  },
  {
    Avatar: "/lawyer_2.jpeg",
    Name: "Olivia Shah",
    Characteristics: "Criminal Defense",
    Rate: 2400,
    rating: 4.7,
    longitude: 72.6024,
    latitude: 23.0264,
    About:
      "Olivia Shah specializes in Criminal Defense and has a 4.7-star rating. She is committed to defending her clients' rights in criminal cases.",
  },
  {
    Avatar: "/lawyer_3.jpeg",
    Name: "Liam Desai",
    Characteristics: "Real Estate Law",
    Rate: 2100,
    rating: 4.8,
    longitude: 72.5953,
    latitude: 23.026,
    About:
      "Liam Desai is a Real Estate Law expert with a 4.8-star rating. He assists clients in navigating real estate transactions and legal matters.",
  },
  {
    Avatar: "/lawyer_4.jpeg",
    Name: "Emma Joshi",
    Characteristics: "Family Law",
    Rate: 2300,
    rating: 4.5,
    longitude: 72.5918,
    latitude: 23.0384,
    About:
      "Emma Joshi is a Family Law attorney with a 4.5-star rating. She is dedicated to helping families resolve legal issues with care and empathy.",
  },
  {
    Avatar: "/lawyer_5.jpeg",
    Name: "Mason Mehta",
    Characteristics: "Business Law",
    Rate: 2500,
    rating: 4.9,
    longitude: 72.6039,
    latitude: 23.032,
    About:
      "Mason Mehta specializes in Business Law and has a 4.9-star rating. He assists businesses in legal matters to ensure their success.",
  },
  {
    Avatar: "/lawyer_6.jpeg",
    Name: "Sophia Kumar",
    Characteristics: "Immigration Law",
    Rate: 2000,
    rating: 4.4,
    longitude: 72.5952,
    latitude: 23.0433,
    About:
      "Sophia Kumar is an Immigration Law expert with a 4.4-star rating. She helps clients navigate immigration processes and achieve their goals.",
  },
  {
    Avatar: "/lawyer_7.jpeg",
    Name: "Ava Gupta",
    Characteristics: "Intellectual Property",
    Rate: 2600,
    rating: 4.7,
    longitude: 72.5965,
    latitude: 23.0331,
    About:
      "Ava Gupta specializes in Intellectual Property Law with a 4.7-star rating. She assists clients in protecting their intellectual property rights.",
  },
  {
    Avatar: "/lawyer_8.jpeg",
    Name: "Noah Patel",
    Characteristics: "Personal Injury",
    Rate: 2200,
    rating: 4.8,
    longitude: 72.5823,
    latitude: 23.0238,
    About:
      "Noah Patel is a Personal Injury attorney with a 4.8-star rating. She fights for the rights of individuals injured due to negligence.",
  },
  {
    Avatar: "/lawyer_9.jpeg",
    Name: "William Shah",
    Characteristics: "Estate Planning",
    Rate: 2300,
    rating: 4.6,
    longitude: 72.5868,
    latitude: 23.0346,
    About:
      "William Shah specializes in Estate Planning and has a 4.6-star rating. He helps clients with estate and wealth preservation strategies.",
  },
  {
    Avatar: "/lawyer_10.jpeg",
    Name: "Olivia Desai",
    Characteristics: "Environmental Law",
    Rate: 2100,
    rating: 4.5,
    longitude: 72.6012,
    latitude: 23.0295,
    About:
      "Olivia Desai is an Environmental Law attorney with a 4.5-star rating. She is dedicated to environmental protection and legal advocacy.",
  },
];

export const JobVadodara = [
  {
    Avatar: "/logo_1.jpg",
    Name: "ABC Tech Solutions",
    Characteristics: "Software Engineer",
    Rate: 75000,
    longitude: 73.1912,
    latitude: 22.3053,
    About:
      "ABC Tech Solutions is a leading IT company offering exciting opportunities for Software Engineers. Join us to work on cutting-edge projects and advance your career.",
  },
  {
    Avatar: "/logo_2.jpg",
    Name: "XYZ Industries",
    Characteristics: "Data Analyst",
    Rate: 65000,
    longitude: 73.2075,
    latitude: 22.3187,
    About:
      "XYZ Industries is seeking Data Analysts to analyze and interpret data for informed decision-making. Join our team and be part of data-driven success.",
  },
  {
    Avatar: "/logo_3.png",
    Name: "Global Finance Corp",
    Characteristics: "Financial Analyst",
    Rate: 80000,
    longitude: 73.1898,
    latitude: 22.3136,
    About:
      "Global Finance Corp offers exciting opportunities for Financial Analysts. Join us to work in a dynamic financial environment and shape the future of finance.",
  },
  {
    Avatar: "/logo_4.png",
    Name: "Tech Innovators",
    Characteristics: "Product Manager",
    Rate: 90000,
    longitude: 73.1945,
    latitude: 22.3094,
    About:
      "Tech Innovators is looking for experienced Product Managers to lead product development. Join us and drive innovation in technology solutions.",
  },
  {
    Avatar: "/logo_5.png",
    Name: "Creative Media Solutions",
    Characteristics: "Graphic Designer",
    Rate: 60000,
    longitude: 73.1996,
    latitude: 22.3158,
    About:
      "Creative Media Solutions seeks talented Graphic Designers to create captivating visuals. Join our team and unleash your creativity.",
  },
  {
    Avatar: "/logo_6.jpg",
    Name: "Mega Corp",
    Characteristics: "Marketing Manager",
    Rate: 85000,
    longitude: 73.1847,
    latitude: 22.3082,
    About:
      "Mega Corp is hiring Marketing Managers to lead marketing strategies. Join us and be part of a high-impact marketing team.",
  },
  {
    Avatar: "/logo_7.png",
    Name: "Tech Wizards Ltd",
    Characteristics: "AI Researcher",
    Rate: 100000,
    longitude: 73.2015,
    latitude: 22.311,
    About:
      "Tech Wizards Ltd is at the forefront of AI research. Join us to explore the future of artificial intelligence and make a difference.",
  },
  {
    Avatar: "/logo_8.jpg",
    Name: "Eco Solutions Inc",
    Characteristics: "Environmental Scientist",
    Rate: 70000,
    longitude: 73.1882,
    latitude: 22.3147,
    About:
      "Eco Solutions Inc is dedicated to environmental conservation. Join our team of Environmental Scientists and contribute to a sustainable future.",
  },
  {
    Avatar: "/logo_9.jpg",
    Name: "Innovative Creations",
    Characteristics: "UX Designer",
    Rate: 72000,
    longitude: 73.2032,
    latitude: 22.3123,
    About:
      "Innovative Creations is seeking UX Designers to craft exceptional user experiences. Join us and shape the usability of digital products.",
  },
  {
    Avatar: "/logo_10.png",
    Name: "Data Systems Ltd",
    Characteristics: "Database Administrator",
    Rate: 78000,
    longitude: 73.1962,
    latitude: 22.3075,
    About:
      "Data Systems Ltd is a leader in data management. Join our team as a Database Administrator and ensure data integrity and performance.",
  },
];

export const JobSurat = [
  {
    Avatar: "/logo_11.png",
    Name: "Surat IT Solutions",
    Characteristics: "Software Engineer",
    Rate: 72000,
    longitude: 72.8156,
    latitude: 21.1648,
    About:
      "Surat IT Solutions offers exciting opportunities for Software Engineers. Join us to work on innovative projects and advance your career in IT.",
  },
  {
    Avatar: "/logo_12.jpg",
    Name: "Surat Analytics",
    Characteristics: "Data Analyst",
    Rate: 65000,
    longitude: 72.8279,
    latitude: 21.1623,
    About:
      "Surat Analytics is looking for Data Analysts to analyze and extract insights from data. Join our team and make data-driven decisions.",
  },
  {
    Avatar: "/logo_13.jpg",
    Name: "Finance Innovators",
    Characteristics: "Financial Analyst",
    Rate: 80000,
    longitude: 72.8094,
    latitude: 21.1567,
    About:
      "Finance Innovators is a pioneer in financial analysis. Join us as a Financial Analyst and help shape the financial landscape.",
  },
  {
    Avatar: "/logo_14.png",
    Name: "Surat Tech Hub",
    Characteristics: "Product Manager",
    Rate: 90000,
    longitude: 72.8314,
    latitude: 21.1725,
    About:
      "Surat Tech Hub is seeking experienced Product Managers to lead product development. Join us and drive innovation in technology.",
  },
  {
    Avatar: "/logo_15.png",
    Name: "Creative Designs",
    Characteristics: "Graphic Designer",
    Rate: 60000,
    longitude: 72.8375,
    latitude: 21.1763,
    About:
      "Creative Designs is hiring Graphic Designers to create visually appealing content. Join our team and bring creativity to life.",
  },
  {
    Avatar: "/logo_16.jpg",
    Name: "Marketing Geniuses",
    Characteristics: "Marketing Manager",
    Rate: 85000,
    longitude: 72.8212,
    latitude: 21.169,
    About:
      "Marketing Geniuses is a dynamic marketing agency. Join us as a Marketing Manager and drive successful marketing campaigns.",
  },
  {
    Avatar: "/logo_17.jpg",
    Name: "AI Innovations",
    Characteristics: "AI Researcher",
    Rate: 100000,
    longitude: 72.8276,
    latitude: 21.1662,
    About:
      "AI Innovations is at the forefront of AI research. Join us to explore the limitless possibilities of artificial intelligence.",
  },
  {
    Avatar: "/logo_18.jpg",
    Name: "EcoSolutions Ltd",
    Characteristics: "Environmental Scientist",
    Rate: 70000,
    longitude: 72.8137,
    latitude: 21.1589,
    About:
      "EcoSolutions Ltd is committed to environmental sustainability. Join our team of Environmental Scientists and make a positive impact.",
  },
  {
    Avatar: "/logo_19.jpg",
    Name: "Surat UX Creations",
    Characteristics: "UX Designer",
    Rate: 75000,
    longitude: 72.8348,
    latitude: 21.1757,
    About:
      "Surat UX Creations is dedicated to creating exceptional user experiences. Join us and design intuitive and user-friendly interfaces.",
  },
  {
    Avatar: "/logo_20.jpg",
    Name: "Data Systems Inc",
    Characteristics: "Database Administrator",
    Rate: 78000,
    longitude: 72.8217,
    latitude: 21.1628,
    About:
      "Data Systems Inc is a leader in database management. Join our team as a Database Administrator and ensure data reliability and performance.",
  },
];

export const JobAhmedabad = [
  {
    Avatar: "/logo_21.jpg",
    Name: "Ahmedabad IT Solutions",
    Characteristics: "Software Engineer",
    Rate: 75000,
    longitude: 72.5875,
    latitude: 23.0221,
    About:
      "Ahmedabad IT Solutions offers exciting opportunities for Software Engineers. Join us to work on innovative software projects and advance your career.",
  },
  {
    Avatar: "/logo_22.jpg",
    Name: "Tech Innovations",
    Characteristics: "Data Analyst",
    Rate: 68000,
    longitude: 72.6024,
    latitude: 23.0264,
    About:
      "Tech Innovations is seeking Data Analysts to analyze and extract insights from data. Join our team and play a key role in data-driven decision-making.",
  },
  {
    Avatar: "/logo_23.jpeg",
    Name: "Finance Masters",
    Characteristics: "Financial Analyst",
    Rate: 80000,
    longitude: 72.5953,
    latitude: 23.026,
    About:
      "Finance Masters is a leading financial institution. Join us as a Financial Analyst and contribute to financial excellence and growth.",
  },
  {
    Avatar: "/logo_24.jpg",
    Name: "Ahmedabad Tech Hub",
    Characteristics: "Product Manager",
    Rate: 90000,
    longitude: 72.5918,
    latitude: 23.0384,
    About:
      "Ahmedabad Tech Hub is seeking experienced Product Managers to lead product development. Join us and shape the future of technology.",
  },
  {
    Avatar: "/logo_25.jpg",
    Name: "Creative Minds",
    Characteristics: "Graphic Designer",
    Rate: 70000,
    longitude: 72.6039,
    latitude: 23.032,
    About:
      "Creative Minds is hiring Graphic Designers to create visually stunning graphics. Join our team and showcase your creative talents.",
  },
  {
    Avatar: "/logo_26.png",
    Name: "Marketing Pro",
    Characteristics: "Marketing Manager",
    Rate: 85000,
    longitude: 72.5952,
    latitude: 23.0433,
    About:
      "Marketing Pro is a dynamic marketing agency. Join us as a Marketing Manager and drive successful marketing campaigns for our clients.",
  },
  {
    Avatar: "/logo_27.jpg",
    Name: "AI Pioneers",
    Characteristics: "AI Researcher",
    Rate: 100000,
    longitude: 72.5965,
    latitude: 23.0331,
    About:
      "AI Pioneers is at the forefront of AI research. Join us to explore the frontiers of artificial intelligence and make groundbreaking discoveries.",
  },
  {
    Avatar: "/logo_28.jpg",
    Name: "EcoTech Ltd",
    Characteristics: "Environmental Scientist",
    Rate: 72000,
    longitude: 72.5823,
    latitude: 23.0238,
    About:
      "EcoTech Ltd is dedicated to environmental preservation. Join our team of Environmental Scientists and contribute to a greener world.",
  },
  {
    Avatar: "/logo_29.jpg",
    Name: "Ahmedabad UX Creations",
    Characteristics: "UX Designer",
    Rate: 78000,
    longitude: 72.5868,
    latitude: 23.0346,
    About:
      "Ahmedabad UX Creations is passionate about creating exceptional user experiences. Join us and design user-centric interfaces that delight users.",
  },
  {
    Avatar: "/logo_30.jpg",
    Name: "Data Systems Inc",
    Characteristics: "Database Administrator",
    Rate: 75000,
    longitude: 72.6012,
    latitude: 23.0295,
    About:
      "Data Systems Inc is a trusted leader in database management. Join our team as a Database Administrator and ensure data reliability and performance.",
  },
];

export const DoctorVadodara = [
  {
    Avatar: "/doctor_1.jpeg",
    Name: "Dr. Smith",
    Characteristics: "Cardiologist",
    Rate: 1500,
    rating: 4.5,
    longitude: 73.1812,
    latitude: 22.3223,
    About:
      "Dr. Smith is a highly experienced Cardiologist dedicated to cardiovascular health. With a commitment to patient care, Dr. Smith offers expert cardiology services.",
  },
  {
    Avatar: "/doctor_2.jpg",
    Name: "Dr. Johnson",
    Characteristics: "Dermatologist",
    Rate: 1200,
    rating: 4.8,
    longitude: 73.1974,
    latitude: 22.3065,
    About:
      "Dr. Johnson is a renowned Dermatologist specializing in skin health and beauty. Experience top-quality dermatological care with Dr. Johnson.",
  },
  {
    Avatar: "/doctor_3.jpg",
    Name: "Dr. Patel",
    Characteristics: "Orthopedic Surgeon",
    Rate: 1800,
    rating: 4.3,
    longitude: 73.1822,
    latitude: 22.3085,
    About:
      "Dr. Patel is a skilled Orthopedic Surgeon with expertise in musculoskeletal health. Trust Dr. Patel for orthopedic solutions and care.",
  },
  {
    Avatar: "/doctor_4.jpg",
    Name: "Dr. Sharma",
    Characteristics: "Pediatrician",
    Rate: 1000,
    rating: 4.9,
    longitude: 73.2173,
    latitude: 22.3224,
    About:
      "Dr. Sharma is a compassionate Pediatrician dedicated to children's well-being. Bring your child to Dr. Sharma for expert pediatric care.",
  },
  {
    Avatar: "/doctor_5.jpg",
    Name: "Dr. Gupta",
    Characteristics: "Ophthalmologist",
    Rate: 1400,
    rating: 4.6,
    longitude: 73.1704,
    latitude: 22.3118,
    About:
      "Dr. Gupta is a skilled Ophthalmologist specializing in eye care. Trust your vision to Dr. Gupta for comprehensive ophthalmological services.",
  },
  {
    Avatar: "/doctor_6.jpeg",
    Name: "Dr. Kumar",
    Characteristics: "Gynecologist",
    Rate: 1600,
    rating: 4.7,
    longitude: 73.1965,
    latitude: 22.3031,
    About:
      "Dr. Kumar is a dedicated Gynecologist providing expert care for women's health. Visit Dr. Kumar for personalized and compassionate gynecological services.",
  },
  {
    Avatar: "/doctor_7.jpeg",
    Name: "Dr. Shah",
    Characteristics: "ENT Specialist",
    Rate: 1300,
    rating: 4.4,
    longitude: 73.2018,
    latitude: 22.304,
    About:
      "Dr. Shah is a skilled ENT Specialist offering comprehensive ear, nose, and throat care. Trust Dr. Shah for expert ENT solutions.",
  },
  {
    Avatar: "/doctor_8.jpeg",
    Name: "Dr. Joshi",
    Characteristics: "Psychiatrist",
    Rate: 1700,
    rating: 4.2,
    longitude: 73.1891,
    latitude: 22.2987,
    About:
      "Dr. Joshi is a compassionate Psychiatrist specializing in mental health. Seek help from Dr. Joshi for expert psychiatric care and support.",
  },
  {
    Avatar: "/doctor_9.jpeg",
    Name: "Dr. Agrawal",
    Characteristics: "General Physician",
    Rate: 1100,
    rating: 4.7,
    longitude: 73.207,
    latitude: 22.3142,
    About:
      "Dr. Agrawal is a caring General Physician providing comprehensive healthcare services. Consult Dr. Agrawal for all your general health needs.",
  },
  {
    Avatar: "/doctor_10.jpeg",
    Name: "Dr. Mehta",
    Characteristics: "Dentist",
    Rate: 1300,
    rating: 4.6,
    longitude: 73.1886,
    latitude: 22.3117,
    About:
      "Dr. Mehta is a skilled Dentist specializing in dental health. Maintain your oral hygiene and dental health with expert care from Dr. Mehta.",
  },
];

export const DoctorSurat = [
  {
    Avatar: "/doctor_1.jpeg",
    Name: "Dr. Patel",
    Characteristics: "Cardiologist",
    Rate: 1500,
    rating: 4.5,
    longitude: 72.8311,
    latitude: 21.169,
    About:
      "Dr. Patel is a dedicated Cardiologist with expertise in cardiovascular health. With a focus on patient well-being, Dr. Patel provides top-notch cardiology services.",
  },
  {
    Avatar: "/doctor_2.jpg",
    Name: "Dr. Shah",
    Characteristics: "Dermatologist",
    Rate: 1200,
    rating: 4.8,
    longitude: 72.8043,
    latitude: 21.1702,
    About:
      "Dr. Shah is a renowned Dermatologist known for skin health and beauty solutions. Experience excellence in dermatological care with Dr. Shah.",
  },
  {
    Avatar: "/doctor_3.jpg",
    Name: "Dr. Joshi",
    Characteristics: "Orthopedic Surgeon",
    Rate: 1800,
    rating: 4.3,
    longitude: 72.8193,
    latitude: 21.1844,
    About:
      "Dr. Joshi is a skilled Orthopedic Surgeon specializing in musculoskeletal health. Trust Dr. Joshi for orthopedic care and surgical expertise.",
  },
  {
    Avatar: "/doctor_4.jpg",
    Name: "Dr. Mehta",
    Characteristics: "Pediatrician",
    Rate: 1000,
    rating: 4.9,
    longitude: 72.8215,
    latitude: 21.1902,
    About:
      "Dr. Mehta is a compassionate Pediatrician dedicated to children's well-being. Choose Dr. Mehta for expert pediatric healthcare.",
  },
  {
    Avatar: "/doctor_5.jpg",
    Name: "Dr. Gupta",
    Characteristics: "Ophthalmologist",
    Rate: 1400,
    rating: 4.6,
    longitude: 72.8273,
    latitude: 21.1964,
    About:
      "Dr. Gupta is a skilled Ophthalmologist providing comprehensive eye care. Entrust your vision to Dr. Gupta for top-quality ophthalmological services.",
  },
  {
    Avatar: "/doctor_6.jpeg",
    Name: "Dr. Kumar",
    Characteristics: "Gynecologist",
    Rate: 1600,
    rating: 4.7,
    longitude: 72.8127,
    latitude: 21.1882,
    About:
      "Dr. Kumar is a dedicated Gynecologist offering specialized care for women's health. Receive personalized and empathetic gynecological services from Dr. Kumar.",
  },
  {
    Avatar: "/doctor_7.jpeg",
    Name: "Dr. Shah",
    Characteristics: "ENT Specialist",
    Rate: 1300,
    rating: 4.4,
    longitude: 72.8353,
    latitude: 21.1756,
    About:
      "Dr. Shah is a skilled ENT Specialist providing comprehensive ear, nose, and throat care. Rely on Dr. Shah for expert ENT solutions.",
  },
  {
    Avatar: "/doctor_8.jpeg",
    Name: "Dr. Desai",
    Characteristics: "Psychiatrist",
    Rate: 1700,
    rating: 4.2,
    longitude: 72.8258,
    latitude: 21.1658,
    About:
      "Dr. Desai is a compassionate Psychiatrist with expertise in mental health. Seek professional psychiatric care and support from Dr. Desai.",
  },
  {
    Avatar: "/doctor_9.jpeg",
    Name: "Dr. Agrawal",
    Characteristics: "General Physician",
    Rate: 1100,
    rating: 4.7,
    longitude: 72.8422,
    latitude: 21.1584,
    About:
      "Dr. Agrawal is a caring General Physician providing holistic healthcare services. Consult Dr. Agrawal for all your general health needs.",
  },
  {
    Avatar: "/doctor_10.jpeg",
    Name: "Dr. Thakkar",
    Characteristics: "Dentist",
    Rate: 1300,
    rating: 4.6,
    longitude: 72.8157,
    latitude: 21.173,
    About:
      "Dr. Thakkar is a skilled Dentist specializing in dental health and hygiene. Maintain your oral health with expert care from Dr. Thakkar.",
  },
];

export const DoctorAhmedabad = [
  {
    Avatar: "/doctor_1.jpeg",
    Name: "Dr. Patel",
    Characteristics: "Cardiologist",
    Rate: 1500,
    rating: 4.5,
    longitude: 72.5873,
    latitude: 23.0225,
    About:
      "Dr. Patel is a highly experienced Cardiologist dedicated to heart health. With a commitment to patient well-being, Dr. Patel provides expert cardiological care.",
  },
  {
    Avatar: "/doctor_2.jpg",
    Name: "Dr. Shah",
    Characteristics: "Dermatologist",
    Rate: 1200,
    rating: 4.8,
    longitude: 72.5986,
    latitude: 23.0338,
    About:
      "Dr. Shah is a renowned Dermatologist specializing in skin care and beauty. Experience top-notch dermatological care with Dr. Shah.",
  },
  {
    Avatar: "/doctor_3.jpg",
    Name: "Dr. Joshi",
    Characteristics: "Orthopedic Surgeon",
    Rate: 1800,
    rating: 4.3,
    longitude: 72.5819,
    latitude: 23.0401,
    About:
      "Dr. Joshi is a skilled Orthopedic Surgeon with expertise in musculoskeletal health. Trust Dr. Joshi for orthopedic care and surgical excellence.",
  },
  {
    Avatar: "/doctor_4.jpg",
    Name: "Dr. Mehta",
    Characteristics: "Pediatrician",
    Rate: 1000,
    rating: 4.9,
    longitude: 72.5983,
    latitude: 23.0391,
    About:
      "Dr. Mehta is a compassionate Pediatrician dedicated to children's well-being. Choose Dr. Mehta for expert pediatric healthcare.",
  },
  {
    Avatar: "/doctor_5.jpg",
    Name: "Dr. Gupta",
    Characteristics: "Ophthalmologist",
    Rate: 1400,
    rating: 4.6,
    longitude: 72.5875,
    latitude: 23.0221,
    About:
      "Dr. Gupta is a skilled Ophthalmologist providing comprehensive eye care. Rely on Dr. Gupta for top-quality ophthalmological services.",
  },
  {
    Avatar: "/doctor_6.jpeg",
    Name: "Dr. Kumar",
    Characteristics: "Gynecologist",
    Rate: 1600,
    rating: 4.7,
    longitude: 72.6055,
    latitude: 23.0372,
    About:
      "Dr. Kumar is a dedicated Gynecologist offering specialized care for women's health. Receive personalized and empathetic gynecological services from Dr. Kumar.",
  },
  {
    Avatar: "/doctor_7.jpeg",
    Name: "Dr. Shah",
    Characteristics: "ENT Specialist",
    Rate: 1300,
    rating: 4.4,
    longitude: 72.6021,
    latitude: 23.0258,
    About:
      "Dr. Shah is a skilled ENT Specialist providing comprehensive ear, nose, and throat care. Rely on Dr. Shah for expert ENT solutions.",
  },
  {
    Avatar: "/doctor_8.jpeg",
    Name: "Dr. Desai",
    Characteristics: "Psychiatrist",
    Rate: 1700,
    rating: 4.2,
    longitude: 72.5851,
    latitude: 23.0302,
    About:
      "Dr. Desai is a compassionate Psychiatrist with expertise in mental health. Seek professional psychiatric care and support from Dr. Desai.",
  },
  {
    Avatar: "/doctor_9.jpeg",
    Name: "Dr. Agrawal",
    Characteristics: "General Physician",
    Rate: 1100,
    rating: 4.7,
    longitude: 72.5948,
    latitude: 23.033,
    About:
      "Dr. Agrawal is a caring General Physician providing holistic healthcare services. Consult Dr. Agrawal for all your general health needs.",
  },
  {
    Avatar: "/doctor_10.jpeg",
    Name: "Dr. Thakkar",
    Characteristics: "Dentist",
    Rate: 1300,
    rating: 4.6,
    longitude: 72.597,
    latitude: 23.0279,
    About:
      "Dr. Thakkar is a skilled Dentist specializing in dental health and hygiene. Maintain your oral health with expert care from Dr. Thakkar.",
  },
];
